### ISSUE TITLE
您好，请问可以给一个依赖包的版本列表吗？

### ISSUE THREAD

**Issue by QuietSugar** [moontide/WeChatBotEngine#4]
我使用自己下载的包，出了了一些问题。

**Comment by moontide** [comment]
郭嘉你好，我好像在 Wiki 里打了个草稿 = =
https://github.com/moontide/WeChatBotEngine/wiki

这是目前我的 `lib` 目录下的 .jar 列表，有些并没用上（比如 apache 的 Http Components）
<pre>
commons-beanutils-1.9.3.jar
commons-codec-1.10.jar
commons-configuration2-2.1.jar
commons-dbcp2-2.1.1.jar
commons-io-2.5.jar
commons-lang3-3.5.jar
commons-logging-1.2.jar
commons-pool2-2.4.2.jar
fluent-hc-4.5.2.jar
httpclient-4.5.2.jar
httpclient-cache-4.5.2.jar
httpclient-win-4.5.2.jar
httpcore-4.4.4.jar
httpmime-4.5.2.jar
jackson-annotations-2.8.4.jar
jackson-core-2.8.4.jar
jackson-databind-2.8.4.jar
jna-4.1.0.jar
jna-platform-4.1.0.jar
jsoup-1.10.1.jar
mysql-connector-java-5.1.40-bin.jar
xom-1.2.10.jar
</pre>

还有：出了一些问题受到伤害时，请遗迹给我红桃，别人乐你我给你改判定 😂 …
可是我是 ⚡ 张角 ⚡ 😜 …

**Comment by QuietSugar** [comment]
第一次在github上面问问题，之前一直一个人单机，当做代码仓库用:joy:。。才发现居然有Wiki这种东西，打开了新世界的大门.....以后请多指教，，， @moontide 我回复的时候是不是要这样@你才行
