### ISSUE TITLE
为什么群消息 无法获取到getUserRemarkName？

### ISSUE THREAD

**Issue by lxhj** [moontide/WeChatBotEngine#8]
请问这个有交流群吗？为什么群消息无法获取到getUserRemarkName？

**Comment by moontide** [comment]
`getUserRemarkName` 是什么？ 代码里搜不到这个文字

**Comment by lxhj** [comment]
private String getUserRemarkName(String id) {}
是一个方法呀 WechatServiceImpl里的，
获取用户名字的，你在群聊里发句话，可以看到 返回的是“这个人物名字未知” ，获取不到用户名。普通的聊天可以获取到。

**Comment by moontide** [comment]
你发错地方了吧，这肯定不是这个项目里的代码。

我看了你发的问题单，在 3 个项目里发类似的问题单。

**Comment by lxhj** [comment]
sry ， 请问这个项目可以再win里跑吗？
